export const UPDATE_NOTE_TITLE_FILTER = 'UPDATE_NOTE_TITLE_FILTER';

export const UPDATE_NEW_NOTE_VALUE = 'UPDATE_NEW_NOTE_VALUE';

export const ADD_NEW_NOTE = 'ADD_NEW_NOTE';
export const REMOVE_NOTE = 'REMOVE_NOTE';
export const TOGGLE_NOTE = 'TOGGLE_NOTE';
export const UPDATE_ALL_AS_ARCHIVE = 'UPDATE_ALL_AS_ARCHIVE';
export const UPDATE_ALL_AS_UNARCHIVE = 'UPDATE_ALL_AS_UNARCHIVE';

export const UPDATE_ALL_NOTES = 'UPDATE_ALL_NOTES';
